### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (false)

### ISSUE THREAD

**Issue by sazr-pm** [Automattic/vip#1295]
## Expected Behavior

Enter command `vip dev-env create --multisite=y --app-code="C:/Users/xyz/Desktop/dev/xyz-vip/wp-content" --slug=sc-local`

Should setup a local environment when running the command: https://docs.wpvip.com/how-tos/local-development/local-enterprise-search/

## Actual Behavior

I get the below error message:

✕ Please contact VIP Support with the following information:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (false)
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.resolve (node:path:167:9)
    at LandoDaemon.getVersions (C:\Users\xyz\AppData\Roaming\npm\node_modules\@automattic\vip\node_modules\lando\lib\daemon.js:214:16)
    at C:\Users\xyz\AppData\Roaming\npm\node_modules\@automattic\vip\node_modules\lando\lib\daemon.js:237:12
    at LandoDaemon.getComposeSeparator (C:\Users\xyz\AppData\Roaming\npm\node_modules\@automattic\vip\node_modules\lando\lib\daemon.js:235:12)
    at C:\Users\xyz\AppData\Roaming\npm\node_modules\@automattic\vip\node_modules\lando\lib\lando.js:117:25
    at new Promise (<anonymous>)
    at bootstrapEngine (C:\Users\xyz\AppData\Roaming\npm\node_modules\@automattic\vip\node_modules\lando\lib\lando.js:116:28)
    at bootstrapRouter (C:\Users\xyz\AppData\Roaming\npm\node_modules\@automattic\vip\node_modules\lando\lib\lando.js:161:27)
    at C:\Users\xyz\AppData\Roaming\npm\node_modules\@automattic\vip\node_modules\lando\lib\lando.js:319:19
From previous event:
    at C:\Users\xyz\AppData\Roaming\npm\node_modules\@automattic\vip\node_modules\lando\lib\lando.js:319:8
From previous event:
    at Lando.bootstrap (C:\Users\xyz\AppData\Roaming\npm\node_modules\@automattic\vip\node_modules\lando\lib\lando.js:264:25)
    at bootstrapLando (C:\Users\xyz\AppData\Roaming\npm\node_modules\@automattic\vip\dist\lib\dev-environment\dev-environment-lando.js:156:15)
    at async C:\Users\xyz\AppData\Roaming\npm\node_modules\@automattic\vip\dist\bin\vip-dev-env-create.js:62:17
    at async Args._args.default.argv (C:\Users\xyz\AppData\Roaming\npm\node_modules\@automattic\vip\dist\lib\cli\command.js:450:11)
Error:  Unexpected error
Debug:  VIP-CLI v2.27.0, Node v16.13.2, win32 10.0.22621

## Steps to Reproduce the Problem

1. Run the command on a computer like mine.

**Comment by sjinks** [comment]
Judging by `LandoDaemon.getVersions` in the stack trace, you don't have `docker-compose` installed. Could you please confirm that it is installed and can be launched from the command line?
