### ISSUE TITLE
Environments with mixed case slugs cannot be started

### ISSUE THREAD

**Issue by sjinks** [Automattic/vip#1635]
## Steps to Reproduce the Problem

```sh
vip dev-env create --slug CaseSensitive < /dev/null
vip dev-env start --slug CaseSensitive
```

## Expected Behavior

The environment starts.

## Actual Behavior

```
Running validation steps...
✓ Check for Docker installation 
✓ Check for docker-compose installation 
✓ Check Docker connectivity 
✓ Check DNS resolution 
The most recent WordPress version available is: 6.4
Environment WordPress version is: 6.4  ... 😎 nice! 
Current local environment version is: 2.0.1
no container to killNo stopped containers
Error:  There was an error reading file "/home/volodymyr/.local/share/vip/dev-environment/casesensitive/instance_data.json": ENOENT: no such file or directory, open '/home/volodymyr/.local/share/vip/dev-environment/casesensitive/instance_data.json'.
Debug:  VIP-CLI v2.36.4-dev.0, Node v20.9.0, linux 6.5.0-14-generic
```

**Comment by sjinks** [comment]
Backtrace:

```
at Object.readFileUtf8 (node:internal/fs/sync:25:18)
at Object.readFileSync (node:fs:441:19)
at readEnvironmentData (vip-cli/dist/lib/dev-environment/dev-environment-core.js:273:42)
at AsyncEvents.<anonymous> (vip-cli/dist/lib/dev-environment/dev-environment-lando.js:170:72)
at Object.onceWrapper (node:events:629:26)
at AsyncEvents.handle (vip-cli/node_modules/lando/lib/events.js:84:25)
at vip-cli/node_modules/lando/lib/events.js:117:21
at tryCatcher (vip-cli/node_modules/bluebird/js/release/util.js:16:23)
at Object.gotValue (vip-cli/node_modules/bluebird/js/release/reduce.js:166:18)
at Object.gotAccum (vip-cli/node_modules/bluebird/js/release/reduce.js:155:25)
at Object.tryCatcher (vip-cli/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (vip-cli/node_modules/bluebird/js/release/promise.js:547:31)
at Promise._settlePromise (vip-cli/node_modules/bluebird/js/release/promise.js:604:18)
at Promise._settlePromiseCtx (vip-cli/node_modules/bluebird/js/release/promise.js:641:10)
at _drainQueueStep (vip-cli/node_modules/bluebird/js/release/async.js:97:12)
at _drainQueue (vip-cli/node_modules/bluebird/js/release/async.js:86:9) {
```

**Comment by sjinks** [comment]
#1636 for backtraces
